title: Building the Peer-to-Peer Internet
email: hello@tomesh.net
description: >-
  Open-source syllabus to explore community mesh networks and distributed applications
  through social activities and various tinkerings with Raspberry Pi and LoRa systems.
baseurl: "/p2p-internet-workshop"
url: "https://tomeshnet.github.io"
twitter_username: tomeshnet
github_username: tomeshnet

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
